### ISSUE TITLE
AssertionError: optimizer diverged

### ISSUE THREAD

**Issue by arielbenitah** [photogeniq/neural-texturize#10]
Hi,
I tried to run your code on one of my own image 
![tex](https://user-images.githubusercontent.com/10816903/85576609-36fe8200-b641-11ea-9fd0-2bb9463bd9e2.png)
and get the following:
![Screenshot from 2020-06-24 17-36-46](https://user-images.githubusercontent.com/10816903/85576778-5e554f00-b641-11ea-9166-37d4f7bb265b.png)
However on your images the code is working fine:
![Screenshot from 2020-06-24 17-39-44](https://user-images.githubusercontent.com/10816903/85577233-bbe99b80-b641-11ea-8632-118e582658e2.png)

I'm using python 3.7 and not python 3.8 - I configure the program by running this setup (remove python 3.8):
![Screenshot from 2020-06-24 17-45-10](https://user-images.githubusercontent.com/10816903/85578184-901ae580-b642-11ea-9610-7f4ba1c8e200.png)

**Do you have any idea about what can be the problem**?

thanks a lot for your help.

Ariel

**Comment by alexjc** [comment]
I'm currently working on this, and will be pushing some updates soon.

In `api.py` you can change `lr=0.1` when creating the `TextureSynthesizer` instead of the default `lr=1.0`.  You'll also need to increase the number of `iterations` accordingly.

**Comment by arielbenitah** [comment]
Hi, thanks a lot for the quick reply. I'll do what you suggested.
Amazing work by the way - thanks for sharing it.

**Comment by alexjc** [comment]
Try with the latest changes in [6bc90ef] and let me know if it's any better!
