### ISSUE TITLE
Requirement for Python 3.7

### ISSUE THREAD

**Issue by Quasimondo** [photogeniq/neural-texturize#2]
Is there a particular reason that you require Python 3.7 as a minimum? I didn't want to upgrade my system and replaced the [tool.poetry.dependencies] inside the pyproject.toml files of neural-texturize and image-encoders with python = "^3.6" and it seems to work just fine.

**Comment by alexjc** [comment]
Good question! The `pyproject.toml` file was auto-generated from a Python 3.7 installation. ;-) I'm currently on 3.8.

I don't recommend people upgrade their system installation, I suggest using a fresh `venv` with Conda.  I will see about dropping the version number for the next release!

**Comment by alexjc** [comment]
OK, shipped and this seems to work fine!
https://github.com/photogeniq/neural-texturize/releases/tag/v0.3
